steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mogufinder-frontend'
      - '-f'
      - 'Dockerfile.prod'
      - '--build-arg'
      - 'VITE_API_URL=${_VITE_API_URL}'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/mogufinder-frontend'
