steps:
  - id: Build frontend image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/mogufinder-frontend'
      - '-f'
      - frontend/Dockerfile.prod
      - '--build-arg'
      - 'VITE_API_URL=${_VITE_API_URL}'
      - '--build-arg'
      - 'VITE_GOOGLE_MAPS_API_KEY=${_VITE_GOOGLE_MAPS_API_KEY}'
      - frontend
  - id: Build backend image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/mogufinder-backend'
      - backend
images:
  - 'gcr.io/$PROJECT_ID/mogufinder-frontend'
  - 'gcr.io/$PROJECT_ID/mogufinder-backend'
substitutions:
  _VITE_API_URL: https://example.com
  _VITE_GOOGLE_MAPS_API_KEY: ""
