services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
      - pnpm-store:/root/.local/share/pnpm/store
      - node_modules:/workspace/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "1"
      WATCHPACK_POLLING: "1"
      HOST: 0.0.0.0
    env_file:
      - .env
    ports:
      - "5173:5173" # Vite
      - "3000:3000" # API server (Express)
    depends_on:
      db:
        condition: service_healthy
    command: bash -lc "if [ ! -d node_modules ]; then pnpm install --frozen-lockfile --yes || pnpm install --yes; fi; pnpm dev"
    tty: true
    stdin_open: true
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer:4
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pnpm-store:
  node_modules:
  pgdata:
