name: "🐞 Bug Report (バグ報告)"
description: "動作上の問題や不具合を報告する．"
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        以下のテンプレートに従い，バグの詳細を記述してください．
  - type: textarea
    id: content
    attributes:
      label: "バグの内容 (Describe the Bug)"
      description: "バグの内容を具体的に記述してください．"
      placeholder: |
        例：A を実行した際に，expected となってほしいが，actual となる．
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: "その他 (Additional Context)"
      description: "その他，補足(問題の提出URLなど)があれば記述してください．"
