name: "🧹 Chore (雑務・メンテナンス)"
description: "リポジトリのメンテナンスや雑務を記録する．"
title: "[Chore]: "
labels: ["chore"]
body:
  - type: markdown
    attributes:
      value: |
        以下のテンプレートに従い，作業の詳細を記述してください．
  - type: dropdown
    id: chore-type
    attributes:
      label: "作業の種類 (Type of Chore)"
      description: "最も近い作業の種類を選択してください．"
      multiple: true
      options:
        - ビルド設定の変更 (Build/CI Configuration)
        - ドキュメントの修正・追加 (Documentation)
        - リファクタリング (Refactoring)
        - その他 (Other)
    validations:
      required: true
  - type: textarea
    id: task-description
    attributes:
      label: "作業内容 (Task Description)"
      description: "どのような作業を行うか，記述してください．"
      placeholder: "例: ドキュメントを更新する．"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: "その他 (Additional Context)"
      description: "その他，補足があれば記述してください．"