name: "♻️ Specification Change (仕様変更)"
description: "既存ライブラリのロジック・インターフェースの仕様変更を提案する．"
title: "[SPEC]: "
labels: ["specification-change", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        以下のテンプレートに従い，仕様変更の詳細を記述してください．
  - type: input
    id: content
    attributes:
      label: "仕様変更の内容 (Describe the Specification Change)"
      description: "仕様変更の内容を具体的に記述してください．"
      placeholder: "例: BIT のインターフェースを変更する．"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: "その他 (Additional Context)"
      description: "その他，補足があれば記述してください．"